from . import pharmacie_categorie
from . import pharmacie_lot
from . import pharmacie_medicament
from . import pharmacie_ordonnance
from . import pharmacie_posologie
from . import pharmacie_reappro
from . import pharmacie_vente
from . import pharmacie_vente_ligne
from . import res_partner
